# tests/test_builtin_rizzo.py
"""Built-in Rizzo Flow: settings in config.json, service generated by the hub,
hidden/protected in the generic server API, dedicated /api/rizzo route."""
import json

import httpx
import pytest

from mcp_hub.config import (
    BUILTIN_RIZZO, Config, HubConfig, RizzoSettings, ServerConfig, load_config,
    rizzo_settings_from_dict, save_config,
)
from mcp_hub.hub_app import build_app
from mcp_hub.manager import HubManager


def _config(**rizzo) -> Config:
    return Config(hub=HubConfig(), servers={}, rizzo=RizzoSettings(**rizzo))


async def _client(manager):
    return httpx.AsyncClient(transport=httpx.ASGITransport(app=build_app(manager)), base_url="http://test")


# ------------------------------------------------------------------ config

def test_default_settings_are_not_written_and_old_files_still_load(tmp_path):
    path = tmp_path / "config.json"
    save_config(Config(hub=HubConfig(), servers={}), path)
    assert "rizzo" not in json.loads(path.read_text())  # older hubs/configs keep their shape
    assert load_config(path).rizzo == RizzoSettings()


def test_settings_roundtrip_under_a_dedicated_key(tmp_path):
    path = tmp_path / "config.json"
    cfg = _config(installDir=r"D:\rizzo", port=9100, ctx=8192, kvType="q4_0", autostart=True)
    save_config(cfg, path)
    raw = json.loads(path.read_text())
    assert raw["rizzo"]["port"] == 9100 and raw["servers"] == {}  # not a generic server row
    assert load_config(path).rizzo == cfg.rizzo


def test_unknown_keys_in_the_rizzo_section_are_ignored(tmp_path):
    path = tmp_path / "config.json"
    path.write_text(json.dumps({"hub": {}, "servers": {}, "rizzo": {"port": 9000, "future": 1}}))
    assert load_config(path).rizzo.port == 9000


def test_legacy_hand_added_rizzo_service_is_adopted(tmp_path):
    """1.0.6 users added 'rizzo-flow' as a generic service: adopt its folder/port."""
    path = tmp_path / "config.json"
    path.write_text(json.dumps({"hub": {}, "servers": {BUILTIN_RIZZO: {
        "enabled": True, "command": "uv", "args": [], "type": "service",
        "cwd": r"C:\x\rizzo\rizzo-flow", "healthUrl": "http://127.0.0.1:9100/health"}}}))
    cfg = load_config(path)
    assert BUILTIN_RIZZO not in cfg.servers
    assert cfg.rizzo.installDir == r"C:\x\rizzo" and cfg.rizzo.port == 9100


@pytest.mark.parametrize("bad", [
    {"port": 80}, {"port": "8017"}, {"ctx": 10}, {"quant": "q2"}, {"kvType": "f32"},
    {"autostart": "yes"}, {"nope": 1}, {"installDir": 5},
])
def test_invalid_settings_are_rejected(bad):
    with pytest.raises((ValueError, TypeError)):
        rizzo_settings_from_dict(bad)


# ----------------------------------------------------------------- manager

def test_not_installed_means_nothing_runs():
    manager = HubManager(_config())
    assert BUILTIN_RIZZO not in manager.status_snapshot()


def test_installed_adds_the_builtin_entry_but_not_to_config_servers():
    manager = HubManager(_config(installDir=r"C:\x\rizzo"))
    snap = manager.status_snapshot()[BUILTIN_RIZZO]
    assert snap["status"] == "stopped" and snap["type"] == "service" and snap["builtin"] is True
    assert snap["port"] == 8017
    assert BUILTIN_RIZZO not in manager.config.servers


@pytest.mark.asyncio
async def test_autostart_controls_start_with_hub(monkeypatch):
    started = []

    async def fake_start(self):
        started.append(self.name)

    monkeypatch.setattr("mcp_hub.manager.ManagedServer.start", fake_start)
    await HubManager(_config(installDir=r"C:\x")).start_all()
    assert started == []  # manual by default: a GPU model never starts behind your back
    await HubManager(_config(installDir=r"C:\x", autostart=True)).start_all()
    assert started == [BUILTIN_RIZZO]


@pytest.mark.asyncio
async def test_apply_rizzo_rebuilds_the_command_line():
    manager = HubManager(_config(installDir=r"C:\x"))
    managed = await manager.apply_rizzo(RizzoSettings(installDir=r"C:\x", ctx=8192, port=9100))
    assert "--ctx" in managed.config.args and "8192" in managed.config.args
    assert manager.status_snapshot()[BUILTIN_RIZZO]["port"] == 9100
    assert await manager.apply_rizzo(RizzoSettings()) is None  # uninstalled
    assert BUILTIN_RIZZO not in manager.status_snapshot()


@pytest.mark.asyncio
async def test_generic_upsert_and_remove_refuse_the_reserved_name():
    manager = HubManager(_config(installDir=r"C:\x"))
    sc = ServerConfig(enabled=False, command="x", args=[])
    with pytest.raises(ValueError):
        await manager.upsert(BUILTIN_RIZZO, sc)
    with pytest.raises(ValueError):
        await manager.remove(BUILTIN_RIZZO)


@pytest.mark.asyncio
async def test_reload_picks_up_changed_settings(tmp_path):
    path = tmp_path / "config.json"
    manager = HubManager(_config())
    save_config(_config(installDir=r"C:\x", port=9200), path)
    added, updated, removed = await manager.reload_from_disk(path)
    assert updated == [BUILTIN_RIZZO] and manager.status_snapshot()[BUILTIN_RIZZO]["port"] == 9200


# --------------------------------------------------------------------- API

@pytest.mark.asyncio
async def test_api_get_and_put_rizzo(monkeypatch):
    saved = []
    monkeypatch.setattr("mcp_hub.management_api.save_config", lambda c: saved.append(c.rizzo))
    manager = HubManager(_config())
    async with await _client(manager) as client:
        assert (await client.get("/api/rizzo")).json() == {
            "settings": {"installDir": None, "port": 8017, "quant": "q4_k_m", "ctx": 16384,
                         "kvType": "q8_0", "autostart": False},
            "status": None}
        resp = await client.put("/api/rizzo", json={"installDir": r"C:\x", "port": 9100, "quant": "q4_k_m",
                                                    "ctx": 16384, "kvType": "q8_0", "autostart": False})
        assert resp.status_code == 200 and resp.json()["status"] == "stopped"
        assert saved[-1].port == 9100
        status = (await client.get("/api/status")).json()["servers"]
        assert status[BUILTIN_RIZZO]["builtin"] is True


@pytest.mark.asyncio
async def test_api_rejects_bad_settings_and_generic_edits(monkeypatch):
    monkeypatch.setattr("mcp_hub.management_api.save_config", lambda c: None)
    manager = HubManager(_config(installDir=r"C:\x"))
    async with await _client(manager) as client:
        bad = await client.put("/api/rizzo", json={"port": 3})
        assert bad.status_code == 400 and "port" in bad.json()["error"]
        body = {"enabled": True, "command": "x", "args": []}
        r1 = await client.post(f"/api/servers/{BUILTIN_RIZZO}", json=body)
        r2 = await client.delete(f"/api/servers/{BUILTIN_RIZZO}")
        assert r1.status_code == 409 and r2.status_code == 409
        assert "Rizzo Flow panel" in r1.json()["error"]
