from __future__ import annotations

import json
import os
import re
import shutil
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Literal

CONFIG_PATH = Path(os.environ.get("LOCALAPPDATA", Path.home())) / "mcp-hub" / "config.json"

_SECRET_KEY_RE = re.compile(r"TOKEN|SECRET|PASS|KEY|AUTH", re.IGNORECASE)


def redact(env: dict[str, str]) -> dict[str, str]:
    return {k: ("***" if _SECRET_KEY_RE.search(k) else v) for k, v in env.items()}


@dataclass
class ServerConfig:
    enabled: bool
    command: str
    args: list[str]
    env: dict[str, str] = field(default_factory=dict)
    concurrency: Literal["exclusive", "parallel"] = "exclusive"
    # `type == "service"`: a plain long-running process (e.g. an HTTP server
    # such as Rizzo Flow) that the hub only starts/stops/monitors. It is not
    # an MCP server: stdio is not proxied, no `/<name>/sse` route is mounted
    # and it is never written into Claude Code's config by `apply`. The
    # fields below apply to services only.
    type: Literal["mcp", "service"] = "mcp"
    cwd: str | None = None
    # URL polled after start; the service is "starting" until it answers 2xx.
    healthUrl: str | None = None
    # TCP port the service listens on (derived from healthUrl when unset);
    # used to refuse a start while the port is taken and to verify it is
    # released after stop.
    port: int | None = None
    healthTimeout: float = 120.0
    # With `enabled`, start the service when the hub starts (default: manual).
    autostart: bool = False

    @property
    def is_service(self) -> bool:
        return self.type == "service"

    @property
    def starts_with_hub(self) -> bool:
        """Whether the hub starts this server at its own startup / on upsert.

        MCP servers: whenever `enabled`. Services: only `enabled` AND
        `autostart`, so a heavy local service (GPU model) is never started
        behind the user's back."""
        return self.enabled and (self.autostart if self.is_service else True)

    @property
    def effective_port(self) -> int | None:
        if self.port is not None:
            return self.port
        if self.healthUrl:
            from urllib.parse import urlparse
            return urlparse(self.healthUrl).port
        return None


_SERVICE_ONLY_FIELDS = ("cwd", "healthUrl", "port", "healthTimeout", "autostart")


def server_to_dict(sc: ServerConfig) -> dict:
    """`asdict`, but MCP servers omit the service-only fields so existing
    entries in config.json keep their original shape."""
    data = asdict(sc)
    if not sc.is_service:
        data.pop("type")
        for key in _SERVICE_ONLY_FIELDS:
            data.pop(key, None)
    return data


@dataclass
class HubConfig:
    host: str = "127.0.0.1"
    port: int = 37450
    authToken: str | None = None
    autostart: bool = False
    checkForUpdates: bool = True
    includeBetaUpdates: bool = False


# Name reserved for the built-in Rizzo Flow service. It is generated by the hub
# from `RizzoSettings` (see the Rizzo Flow tab in the GUI): never stored in
# `servers`, never editable/removable through the generic server API.
BUILTIN_RIZZO = "rizzo-flow"
RIZZO_QUANTS = ("q4_k_m", "q8_0")
RIZZO_KV_TYPES = ("f16", "q8_0", "q4_0")


@dataclass
class RizzoSettings:
    """Settings of the built-in Rizzo Flow server. `installDir` is None until
    Rizzo is installed/adopted from the GUI; while None the hub runs nothing."""
    installDir: str | None = None
    port: int = 8017
    quant: str = "q4_k_m"
    ctx: int = 16384
    kvType: str = "q8_0"
    autostart: bool = False

    @property
    def rizzo_dir(self) -> Path | None:
        return Path(self.installDir) / "rizzo-flow" if self.installDir else None

    def to_service(self) -> ServerConfig | None:
        """The service the hub runs for these settings (None when not installed).

        `--ctx`/`--kv-type`/`--port` are always passed explicitly so it also
        works with an upstream Rizzo whose defaults are different."""
        if not self.installDir:
            return None
        return ServerConfig(
            enabled=True, command="uv",
            args=["run", "rizzo", "serve", "--size", "4b", "--quant", self.quant, "--device", "cuda",
                  "--ctx", str(self.ctx), "--kv-type", self.kvType, "--port", str(self.port)],
            type="service", cwd=str(self.rizzo_dir),
            healthUrl=f"http://127.0.0.1:{self.port}/health", port=self.port,
            healthTimeout=180.0, autostart=self.autostart,
        )


def rizzo_settings_from_dict(data: dict) -> RizzoSettings:
    """Validates user/API input; raises ValueError with a readable message."""
    known = {f for f in RizzoSettings.__dataclass_fields__}
    unknown = set(data) - known
    if unknown:
        raise ValueError(f"unknown settings: {', '.join(sorted(unknown))}")
    settings = RizzoSettings(**data)
    if settings.installDir is not None and not isinstance(settings.installDir, str):
        raise ValueError("installDir must be a string")
    if not isinstance(settings.port, int) or isinstance(settings.port, bool) or not 1024 <= settings.port <= 65535:
        raise ValueError("port must be an integer between 1024 and 65535")
    if not isinstance(settings.ctx, int) or isinstance(settings.ctx, bool) or not 2048 <= settings.ctx <= 262144:
        raise ValueError("ctx must be an integer between 2048 and 262144")
    if settings.quant not in RIZZO_QUANTS:
        raise ValueError(f"quant must be one of {', '.join(RIZZO_QUANTS)}")
    if settings.kvType not in RIZZO_KV_TYPES:
        raise ValueError(f"kvType must be one of {', '.join(RIZZO_KV_TYPES)}")
    if not isinstance(settings.autostart, bool):
        raise ValueError("autostart must be a boolean")
    return settings


@dataclass
class Config:
    hub: HubConfig
    servers: dict[str, ServerConfig]
    rizzo: RizzoSettings = field(default_factory=RizzoSettings)


def load_config(path: Path | None = None) -> Config:
    # Resolved per call, not bound at import, so a patched CONFIG_PATH is honoured.
    path = path if path is not None else CONFIG_PATH
    if not path.exists():
        return Config(hub=HubConfig(), servers={})
    raw = json.loads(path.read_text(encoding="utf-8"))
    hub = HubConfig(**raw.get("hub", {}))
    servers = {name: ServerConfig(**sc) for name, sc in raw.get("servers", {}).items()}
    known = set(RizzoSettings.__dataclass_fields__)
    rizzo = RizzoSettings(**{k: v for k, v in raw.get("rizzo", {}).items() if k in known})
    # 1.0.6 let you add Rizzo by hand as a generic service named "rizzo-flow":
    # adopt it into the built-in settings (its folder/port) instead of keeping
    # a second entry that would clash with the reserved name.
    legacy = servers.get(BUILTIN_RIZZO)
    if legacy is not None and legacy.is_service:
        if rizzo.installDir is None and legacy.cwd:
            rizzo.installDir = str(Path(legacy.cwd).parent)
            if legacy.effective_port:
                rizzo.port = legacy.effective_port
        del servers[BUILTIN_RIZZO]
    return Config(hub=hub, servers=servers, rizzo=rizzo)


BACKUP_DIR_NAME = "backups"
BACKUP_KEEP = 30


def list_backups(path: Path | None = None) -> list[Path]:
    """Config backups next to `path`, newest first."""
    path = path if path is not None else CONFIG_PATH
    folder = path.parent / BACKUP_DIR_NAME
    if not folder.is_dir():
        return []
    return sorted(folder.glob(f"{path.stem}.*.json"),
                  key=lambda p: (p.stat().st_mtime_ns, p.name), reverse=True)


def _backup_existing(path: Path, new_content: bytes) -> None:
    """Copies the current file to backups/ before it is overwritten, so a bad
    write (a bug, a test, a hand edit) never destroys the only copy of the
    server definitions. Skipped when identical to the newest backup; only the
    newest BACKUP_KEEP are kept. Never raises: a failed backup must not block
    saving the config."""
    try:
        if not path.is_file() or path.stat().st_size == 0:
            return
        current = path.read_bytes()
        # write_text() stores CRLF on Windows: compare line-ending-insensitively.
        if current.replace(b"\r\n", b"\n") == new_content:
            return  # the save changes nothing: no need for a copy
        existing = list_backups(path)
        if existing and existing[0].read_bytes() == current:
            return
        folder = path.parent / BACKUP_DIR_NAME
        folder.mkdir(parents=True, exist_ok=True)
        stamp = time.strftime("%Y%m%d-%H%M%S")
        target = folder / f"{path.stem}.{stamp}.json"
        counter = 1
        while target.exists():
            target = folder / f"{path.stem}.{stamp}-{counter}.json"
            counter += 1
        shutil.copy2(path, target)
        for old in list_backups(path)[BACKUP_KEEP:]:
            old.unlink(missing_ok=True)
    except OSError:
        pass


def save_config(config: Config, path: Path | None = None) -> None:
    path = path if path is not None else CONFIG_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "hub": asdict(config.hub),
        "servers": {name: server_to_dict(sc) for name, sc in config.servers.items()},
    }
    # Only written once configured; older hubs ignore unknown top-level keys.
    if config.rizzo != RizzoSettings():
        payload["rizzo"] = asdict(config.rizzo)
    tmp_path = path.with_suffix(".json.tmp")
    text = json.dumps(payload, indent=2)
    _backup_existing(path, text.encode("utf-8"))
    tmp_path.write_text(text, encoding="utf-8")
    os.replace(tmp_path, path)
